feat: drop node v12
webpack-contrib/eslint-webpack-plugin pull request #159
Opened 2022-05-13 15:27 UTC by amareshsm

Drop node 12 and upgraded dependencies.

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case
Drop node 12 and upgraded dependencies.

### Breaking Changes
yes, removed node v12 support

2022-06-10 18:57 UTC, amareshsm commented
Bump

2022-06-17 20:01 UTC, amareshsm commented
Bumping for review.

2022-06-20 12:59 UTC, ricardogobbosouza requested changes
Could you change the `README `?
Its v8 now

```
You also need to install eslint >= 7 from npm, if you haven't already:
```

2022-06-20 12:59 UTC, ricardogobbosouza commented on babel.config.js
> +            node: '14.17.0',
The default is `14.15.0`

2022-06-20 12:59 UTC, ricardogobbosouza commented on package.json
> +    "node": ">= 14.17.0"
The default is `14.15.0`

2022-06-20 12:59 UTC, ricardogobbosouza commented on package.json
>      "@types/eslint": "^7.28.2 || ^8.2.0",
With this change in node version also need to remove eslint 7 support

2022-06-25 09:50 UTC, amareshsm commented
Bumping for review.

2022-07-02 11:55 UTC, merged