support resourceQueryExclude option
webpack-contrib/eslint-webpack-plugin pull request #165
Opened 2022-06-13 10:36 UTC by ben-lau

This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
#164 
### Breaking Changes
### Additional Info

2022-06-19 12:02 UTC, ricardogobbosouza requested changes

2022-06-20 04:08 UTC, ben-lau commented on commitlint.config.js
> +    'footer-max-line-length': [0],
ok, but it's changed by prettier

2022-06-20 06:20 UTC, ben-lau commented on src/index.js
> +        this.run(c, options, wanted, exclude, options.resourceQueryExclude)
I understand, but the input options has been changed during `apply`, its not same as the type of origin option, so I pass the fourth parameter. However, I can fix it by changing the option type at function `run`

2022-06-20 12:48 UTC, ricardogobbosouza commented
Please resolve conflicts too
`declarations` move to `types`

2022-06-21 02:18 UTC, ben-lau commented on src/index.js
> +   * @param {Omit<Options, 'resourceQueryExclude'> & {resourceQueryExclude: RegExp[]}} options
The `resourceQueryExclude` in type Options is `RegExp` or `RegExp[]`, but in this function resourceQueryExclude type must be `RegExp[]` which changed in `apply`

2022-06-21 02:36 UTC, ben-lau commented on src/index.js
> +   * @param {Omit<Options, 'resourceQueryExclude'> & {resourceQueryExclude: RegExp[]}} options
![image](https://user-images.githubusercontent.com/16952163/174704345-840f113f-3d10-4215-ac26-ee2281227bcf.png)

2022-06-21 02:36 UTC, ben-lau commented
> Please, resolve conflicts too. `declarations` moved to `types`

Sure, I will fetch the upstream

2022-06-23 13:02 UTC, merged