Support flat config
webpack-contrib/eslint-webpack-plugin pull request #238
Opened 2023-12-23 08:19 UTC by onigoetz

This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

As explained in #190, ESLint has a new config system.
This is meant to be the future default but it does not work out of the box.

This PR aims to allow the usage of flat configuration for pioneers while being future proof at the same time.

### Breaking Changes

None

### Additional Info

The new API is documented here: https://eslint.org/blog/2022/08/new-config-system-part-3/

Changes introduced by this PR:
* new `configType` option to allow to switch between the legacy and future way of loading configuration
* moved all code to load eslint to `worker.js` (was duplicated in `getESLint.js` as well)

Each change is in its own commit, you can review them separately.

This replaces #237. 
Once this one is merged I'd happily make another PR for the changes I proposed in tests, but let's not pile everything together.

2023-12-23 10:01 UTC, ricardogobbosouza commented
Muito bom!
Minhas considerações 

1 - Criar uma opcao `flatConfigFile` que ira definir:
- o `eslintPath` como `eslint/use-at-your-own-risk`
- E ja definara o `configType` como flat

2 - Adicionar uma secao no readme sobre `flatConfigFile`

2023-12-23 10:12 UTC, ricardogobbosouza commented
Very good!

Thinking about the user's use, they need to do the following:

```js
const ESLintPlugin = require('eslint-webpack-plugin');

module.exports = {
  // ...
  plugins: [new ESLintPlugin({
    configType: 'flat',
    eslintPath: 'eslint/use-at-your-own-risk',
    overrideConfigFile: 'flat-config.js',
  })],
  // ...
};
```

We could think of a new `flatConfigFile` option

```js
const ESLintPlugin = require('eslint-webpack-plugin');

module.exports = {
  // ...
  plugins: [new ESLintPlugin({
    flatConfigFile: 'flat-config.js',
  })],
  // ...
};
```

1 - Create a `flatConfigFile` option that will define:
  - The `eslintPath` as `eslint/use-at-your-own-risk`
  - The `configType` option becomes unnecessary because with `flatConfigFile` this will be defined automatically
2 - Automatically define `flatConfigFile` if there is an `eslint.config.js` file in the project root (another PR)
3 - Add a section in the readme about `flatConfigFile`

2023-12-23 10:24 UTC, ricardogobbosouza commented
Maybe this new `flatConfigFile` option should be a new PR

2023-12-23 10:31 UTC, ricardogobbosouza commented
@onigoetz  Very good

2023-12-23 13:53 UTC, onigoetz commented
Hi @ricardogobbosouza 

I saw your previous messages, I'm not sure if a new config file key that's changes the import is better.
My current understanding, as per these blog posts: 
- https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/
- https://eslint.org/blog/2023/10/flat-config-rollout-plans/

> The ESLint class will now be equivalent to the FlatESLint class in v8.x. With the exception of a few options, this should mostly be a transparent change.

Is that the default export starting with ESLint 9 will be the flat config.
So maybe there is something to do with imports to auto-detect ESLint's version or imports to differentiate which one we have loaded? I expect this part of the logic to become more complicated once ESLint 9 is released

2023-12-23 17:48 UTC, ricardogobbosouza requested changes
a note in the readme would be nice

2023-12-25 08:18 UTC, onigoetz commented
> a note in the readme would be nice

Sure, done :)

However, I'm not sure why Node 16 is failing :/

2023-12-28 18:10 UTC, ricardogobbosouza commented
@onigoetz 
the message of your commits must be in lowercase letters

2023-12-29 09:11 UTC, onigoetz commented
@ricardogobbosouza sure, done

2023-12-29 16:34 UTC, ricardogobbosouza commented
It's failing on node 18 too

2023-12-29 17:24 UTC, ricardogobbosouza commented
Using node 18 I have the error `Segmentation fault`
Only in test `flat-config.test.js`
Any ideas @alexander-akait?

2023-12-30 08:32 UTC, alexander-akait commented
It is the problem of jest, it is sad, yeah, just skip it for old nodes

2024-01-02 16:43 UTC, merged